### ISSUE TITLE
FEATURE TODO LIST

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/create-remax-app#1]
需支持以下功能：

- [x] 可以选择 JavaScript 和 TypeScript
- [x] 根据模板版本，进行缓存模板 #5 
- [x] 优化 TypeScript #3 
- [x] 模块抽离 #4 
- [x] 集成单元测试 #7

**Comment by yesmeck** [comment]
可以考虑模板全部用 ts 写，然后用 https://github.com/umijs/sylvanas/ 转换到 js

**Comment by QC-L** [comment]
这个后面考虑，我先把基本一些优化搞定。
上述 4 点，搞定 release 一版~
